[package]
name = "restate-metadata-store"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
options_schema = ["dep:schemars"]
test-util = []

[dependencies]
codederror = { workspace = true }
restate-core = { workspace = true }
restate-rocksdb = { workspace = true }
restate-types = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
bytestring = { workspace = true }
derive_builder = { workspace = true }
futures = { workspace = true }
humantime = { workspace = true }
prost-0-12 = { workspace = true }
prost-types-0-12 = { workspace = true }
rocksdb = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic-0-10 = { workspace = true, features = ["transport", "codegen", "prost"] }
tonic-reflection-0-10 = { workspace = true }
tonic-health-0-10 = { workspace = true }
tower = { workspace = true }
tower-http-0-4 = { package = "tower-http", version = "0.4", features = ["trace"] }
tracing = { workspace = true }

[dev-dependencies]
restate-core = { workspace = true, features = ["test-util"] }
restate-rocksdb = { workspace = true, features = ["test-util"] }

anyhow = { workspace = true }
flexbuffers = { workspace = true }
googletest = { workspace = true }
tempfile = { workspace = true }
test-log = { workspace = true }
tracing-subscriber = { workspace = true }

[build-dependencies]
tonic-build-0-11 = { workspace = true }
