[package]
name = "restate-test-util"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
prost = ["dep:prost-0-12"]

[dependencies]
assert2 = { workspace = true }
googletest = { workspace = true }
pretty_assertions = "1.3"
prost-0-12 = { workspace = true, optional = true }

[dev-dependencies]
prost-types-0-12 = { workspace = true }
